from enum import Enum


class TriggerTypes(Enum):
    """Enumeration for Trigger Types

    Values:
        SCHEDULED (str): Scheduled trigger type
        MANUAL (str): Manual trigger type
        S3_TRIGGER (str) = S3 Trigger type
    """
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"
    S3_TRIGGER = "S3_TRIGGER"


class ValidationResultTypes(Enum):
    """Enumeration for Validation Results

    Values:
        PASS (str): Validation passed
        FAIL (str): Validation failed
    """
    PASS = "PASS"
    FAIL = "FAIL"


class FileValidationTypes(Enum):
    """Enumeration for File Validation Types

    Values:
        FILE_EXIST_CHECK (str): Check if the file exists
        FILE_ENCODE_CHECK (str): Check file encoding
        FILE_SIZE_CHECK (str): Check file size
        FILE_DELIMITER_CHECK = "FILE_DELIMITER_CHECK"
        FILE_EXTENSION_CHECK = "FILE_EXTENSION_CHECK"
    """
    FILE_EXIST_CHECK = "FILE_EXIST_CHECK"
    FILE_ENCODE_CHECK = "FILE_ENCODE_CHECK"
    FILE_SIZE_CHECK = "FILE_SIZE_CHECK"
    FILE_DELIMITER_CHECK = "FILE_DELIMITER_CHECK"
    FILE_EXTENSION_CHECK = "FILE_EXTENSION_CHECK"


class SchemaValidationTypes(Enum):
    """Enumeration for Schema Validation Types

    Values:
        TOTAL_COLUMNS = "TOTAL_COLUMNS_CHECK"
        ADDITIONAL_COLUMNS_CHECK = "ADDITIONAL_COLUMNS_CHECK"
        MISSING_CONTENT_CHECK = "MISSING_CONTENT_CHECK"
        TOTAL_NULL_COUNT = "TOTAL_NULL_COUNT"
        DUPLICATE_RECORDS_BY_ROW = "DUPLICATE_RECORDS_BY_ROW"
        DATA_CHECK_FAILURE = "DATA_CHECK_FAILURE"
        RANGE_ROWS_CHECK = "RANGE_ROWS_CHECK"
        LIST_VALUES_ROWS_CHECK = "LIST_VALUES_ROWS_CHECK"
        NUMBER_OF_RANGE_MISMATCH = "NUMBER_OF_RANGE_MISMATCH"
        NUMBER_OF_LIST_VALUE_ERROR = "NUMBER_OF_LIST_VALUE_ERROR"
        NUMBER_OF_RANGE_MISMATCH_SUCCESS = "NUMBER_OF_RANGE_MISMATCH_SUCCESS"
        NUMBER_OF_LIST_VALUE_SUCCESS = "NUMBER_OF_LIST_VALUE_SUCCESS"
        RANGE_MISMATCH_COUNT = "RANGE_MISMATCH_COUNT"
        LIST_VALUE_COUNT = "LIST_VALUE_COUNT"
        MISSING_COLUMNS_CHECK = "MISSING_COLUMNS_CHECK"
        COLUMNS_DATATYPE_CHECK = "COLUMNS_DATATYPE_CHECK"
        RANGE_CHECK = "RANGE_CHECK"
        DUPLICATE_RECORD_CHECK = "DUPLICATE_RECORD_CHECK"
        LIST_VALUES_CHECK = "LIST_VALUES_CHECK"
    """

    TOTAL_COLUMNS = "TOTAL_COLUMNS_CHECK"
    ADDITIONAL_COLUMNS_CHECK = "ADDITIONAL_COLUMNS_CHECK"
    MISSING_CONTENT_CHECK = "MISSING_CONTENT_CHECK"
    TOTAL_NULL_COUNT = "TOTAL_NULL_COUNT"
    DUPLICATE_RECORDS_BY_ROW = "DUPLICATE_RECORDS_BY_ROW"
    DATA_CHECK_FAILURE = "DATA_CHECK_FAILURE"
    RANGE_ROWS_CHECK = "RANGE_ROWS_CHECK"
    LIST_VALUES_ROWS_CHECK = "LIST_VALUES_ROWS_CHECK"
    NUMBER_OF_RANGE_MISMATCH = "NUMBER_OF_RANGE_MISMATCH"
    NUMBER_OF_LIST_VALUE_ERROR = "NUMBER_OF_LIST_VALUE_ERROR"
    NUMBER_OF_RANGE_MISMATCH_SUCCESS = "NUMBER_OF_RANGE_MISMATCH_SUCCESS"
    NUMBER_OF_LIST_VALUE_SUCCESS = "NUMBER_OF_LIST_VALUE_SUCCESS"
    RANGE_MISMATCH_COUNT = "RANGE_MISMATCH_COUNT"
    LIST_VALUE_COUNT = "LIST_VALUE_COUNT"
    MISSING_COLUMNS_CHECK = "MISSING_COLUMNS_CHECK"
    COLUMNS_DATATYPE_CHECK = "COLUMNS_DATATYPE_CHECK"
    RANGE_CHECK = "RANGE_CHECK"
    DUPLICATE_RECORD_CHECK = "DUPLICATE_RECORD_CHECK"
    LIST_VALUES_CHECK = "LIST_VALUES_CHECK"


class ColumnValidationTypes(Enum):
    """Enumeration for Column Validation Types

    Values:
        ADDITIONAL_COLUMNS_CHECK = "ADDITIONAL_COLUMNS_CHECK"
        MISSING_COLUMNS_CHECK = "MISSING_COLUMNS_CHECK"
        COLUMNS_DATATYPE_CHECK = "COLUMNS_DATATYPE_CHECK"
    """
    ADDITIONAL_COLUMNS_CHECK = "ADDITIONAL_COLUMNS_CHECK"
    MISSING_COLUMNS_CHECK = "MISSING_COLUMNS_CHECK"
    COLUMNS_DATATYPE_CHECK = "COLUMNS_DATATYPE_CHECK"


class DataValidationTypes(Enum):
    """Enumeration for Data Validation Types

    Values:
        RANGE_CHECK = "RANGE_CHECK"
        DUPLICATE_RECORD_CHECK = "DUPLICATE_RECORD_CHECK"
        LIST_VALUES_CHECK = "LIST_VALUES_CHECK"
    """
    RANGE_CHECK = "RANGE_CHECK"
    DUPLICATE_RECORD_CHECK = "DUPLICATE_RECORD_CHECK"
    LIST_VALUES_CHECK = "LIST_VALUES_CHECK"


class JobValidationTypes(Enum):
    """Enumeration for Job Validation Types

    Values:
        PASSED = "PASSED"
        FAILED = "FAILED"
    """

    PASSED = "PASSED"
    FAILED = "FAILED"
